application: fardaastationapi
runtime: python27
api_version: 1
threadsafe: true
version: 0

handlers:
- url: /static
  static_dir: static
- url: /static/(.*\.json)
  static_files: /static/\1
  upload: /static/(.*\.json)
  mime_type: application/json
- url: /static/(.*\.txt)
  static_files: /static/\1
  upload: /static/(.*\.txt)
  mime_type: application/text
- url: /.*
  script: FardaaStationAPI.app