runtime: python27
threadsafe: true
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /.*
  script: main.app

env_variables:
    owner_name: "SINA SOLAIMANPOUR"

beta_settings:
    cloud_sql_instances: "fardastationapi:us-east1:fardaastationapi-db"