import os

SECRET_KEY = 'secret'

DATA_BACKEND = 'cloudsql'
PROJECT_ID = 'fardaastationapi'

CLOUDSQL_USER = 'root'
CLOUDSQL_PASSWORD = ''
CLOUDSQL_DATABASE = 'test'
# CLOUDSQL_DATABASE = 'fardaastation'

CLOUDSQL_CONNECTION_NAME = ''

GOOGLE_OAUTH2_CLIENT_ID = \
    ''

GOOGLE_OAUTH2_CLIENT_SECRET = ''