SECRET_KEY = 'secret'

DATA_BACKEND = 'cloudsql'
PROJECT_ID = 'fardaastationapi'

CLOUDSQL_USER = ''
CLOUDSQL_PASSWORD = ''
CLOUDSQL_DATABASE = ''

CLOUDSQL_CONNECTION_NAME = ''

GOOGLE_OAUTH2_CLIENT_ID = \
    ''

GOOGLE_OAUTH2_CLIENT_SECRET = ''